name: Integration Tests with Supabase

on:
  pull_request:
    branches:
      - main
    paths: &watched_paths
      - 'config/**'
      - 'assets/**'
      - 'lib/**'
      - 'priv/**'
      - 'mix.exs'
      - 'mix.lock'
      - 'Dockerfile'
      - 'run.sh'
      - 'test/e2e/supabase/**'
      - '.github/workflows/integration-supabase.yml'
      - '.github/workflows/_integration-supabase.yml'
  push:
    branches:
      - main
    paths: *watched_paths

# Cancel old builds on new commit for same workflow + branch/PR
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  postgres:
    name: Postgres backend
    uses: ./.github/workflows/_integration-supabase.yml
    with:
      backend: postgres

  bigquery:
    name: BigQuery backend
    uses: ./.github/workflows/_integration-supabase.yml
    with:
      backend: bigquery
    secrets: inherit
